// ข้อมูลพยัญชนะไทย ๔๔ ตัว ครบถ้วน พร้อมคำอ่านสะกดสัทศาสตร์เพื่อเสียงพูดถูกต้อง 100%
const THAI_ALPHABET_DATA = [
  {
    id: 1,
    char: "ก",
    word: "ไก่",
    full: "ก ไก่",
    spokenFull: "กอ ไก่",
    phonics: "กอ",
    spokenPhonics: "ออกเสียง กอ",
    readText: "ก ไก่",
    poem: "กอ เอ๋ย กอ ไก่",
    spokenPoem: "กอ เอ๋ย กอ ไก่",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/01.png",
    examples: ["กา", "กบ", "กล้วย"],
    eng: "Ko Kai"
  },
  {
    id: 2,
    char: "ข",
    word: "ไข่",
    full: "ข ไข่",
    spokenFull: "ขอ ไข่",
    phonics: "ขอ",
    spokenPhonics: "ออกเสียง ขอ",
    readText: "ข ไข่",
    poem: "ขอ ไข่ ในเล้า",
    spokenPoem: "ขอ ไข่ ในเล้า",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/02.png",
    examples: ["ขา", "ข้าว", "เข็ม"],
    eng: "Kho Khai"
  },
  {
    id: 3,
    char: "ฃ",
    word: "ขวด",
    full: "ฃ ขวด",
    spokenFull: "ขอ ขวด",
    phonics: "ขอ",
    spokenPhonics: "ออกเสียง ขอ",
    readText: "ฃ ขวด",
    poem: "ฃอ ขวด ของเรา",
    spokenPoem: "ขอ ขวด ของเรา",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/03.png",
    examples: [],
    eng: "Kho Khuat"
  },
  {
    id: 4,
    char: "ค",
    word: "ควาย",
    full: "ค ควาย",
    spokenFull: "คอ ควาย",
    phonics: "คอ",
    spokenPhonics: "ออกเสียง คอ",
    readText: "ค ควาย",
    poem: "คอ ควาย เข้านา",
    spokenPoem: "คอ ควาย เข้านา",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/04.png",
    examples: ["ค้อน", "ครู", "เค้ก"],
    eng: "Kho Khwai"
  },
  {
    id: 5,
    char: "ฅ",
    word: "คน",
    full: "ฅ คน",
    spokenFull: "คอ คน",
    phonics: "คอ",
    spokenPhonics: "ออกเสียง คอ",
    readText: "ฅ คน",
    poem: "ฅอ คน ขึงขัง",
    spokenPoem: "คอ คน ขึงขัง",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/05.png",
    examples: [],
    eng: "Kho Khon"
  },
  {
    id: 6,
    char: "ฆ",
    word: "ระฆัง",
    full: "ฆ ระฆัง",
    spokenFull: "คอ ระฆัง",
    phonics: "คอ",
    spokenPhonics: "ออกเสียง คอ",
    readText: "ฆ ระฆัง",
    poem: "ฆอ ระฆัง ข้างฝา",
    spokenPoem: "คอ ระฆัง ข้างฝา",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/06.png",
    examples: ["ฆ้อง", "โฆษณา", "ฆาตกร"],
    eng: "Kho Rakhang"
  },
  {
    id: 7,
    char: "ง",
    word: "งู",
    full: "ง งู",
    spokenFull: "งอ งู",
    phonics: "งอ",
    spokenPhonics: "ออกเสียง งอ",
    readText: "ง งู",
    poem: "งอ งู ใจกล้า",
    spokenPoem: "งอ งู ใจกล้า",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/07.png",
    examples: ["เงาะ", "เงิน", "งาน"],
    eng: "Ngo Ngu"
  },
  {
    id: 8,
    char: "จ",
    word: "จาน",
    full: "จ จาน",
    spokenFull: "จอ จาน",
    phonics: "จอ",
    spokenPhonics: "ออกเสียง จอ",
    readText: "จ จาน",
    poem: "จอ จาน ใช้ดี",
    spokenPoem: "จอ จาน ใช้ดี",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/08.png",
    examples: ["จดหมาย", "จรวด", "จิงโจ้"],
    eng: "Cho Chan"
  },
  {
    id: 9,
    char: "ฉ",
    word: "ฉิ่ง",
    full: "ฉ ฉิ่ง",
    spokenFull: "ฉอ ฉิ่ง",
    phonics: "ฉอ",
    spokenPhonics: "ออกเสียง ฉอ",
    readText: "ฉ ฉิ่ง",
    poem: "ฉอ ฉิ่ง ตีดัง",
    spokenPoem: "ฉอ ฉิ่ง ตีดัง",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/09.png",
    examples: ["ฉลาม", "ฉัตร", "ฉลาก"],
    eng: "Cho Ching"
  },
  {
    id: 10,
    char: "ช",
    word: "ช้าง",
    full: "ช ช้าง",
    spokenFull: "ชอ ช้าง",
    phonics: "ชอ",
    spokenPhonics: "ออกเสียง ชอ",
    readText: "ช ช้าง",
    poem: "ชอ ช้าง วิ่งหนี",
    spokenPoem: "ชอ ช้าง วิ่งหนี",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/10.png",
    examples: ["ช้อน", "ชาม", "ชมพู่"],
    eng: "Cho Chang"
  },
  {
    id: 11,
    char: "ซ",
    word: "โซ่",
    full: "ซ โซ่",
    spokenFull: "ซอ โซ่",
    phonics: "ซอ",
    spokenPhonics: "ออกเสียง ซอ",
    readText: "ซ โซ่",
    poem: "ซอ โซ่ ล่ามที",
    spokenPoem: "ซอ โซ่ ล่ามที",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/11.png",
    examples: ["ซอส", "ซาลาเปา", "ซากุระ"],
    eng: "So So"
  },

  // แถวที่ 2
  {
    id: 12,
    char: "ฌ",
    word: "เฌอ",
    full: "ฌ เฌอ",
    spokenFull: "ชอ กะเฌอ",
    phonics: "ชอ",
    spokenPhonics: "ออกเสียง ชอ",
    readText: "ฌ เฌอ",
    poem: "ฌอ กะเฌอ คู่กัน",
    spokenPoem: "ชอ กะเฌอ คู่กัน",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/12.png",
    examples: ["ฌาน", "ฌาปนกิจ", "ฌาปนสถาน"],
    eng: "Cho Choe"
  },
  {
    id: 13,
    char: "ญ",
    word: "หญิง",
    full: "ญ หญิง",
    spokenFull: "ยอ หญิง",
    phonics: "ยอ",
    spokenPhonics: "ออกเสียง ยอ",
    readText: "ญ หญิง",
    poem: "ญอ หญิง โสภา",
    spokenPoem: "ยอ หญิง โสภา",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/13.png",
    examples: ["ญาติ", "ญี่ปุ่น", "ญาณ"],
    eng: "Yo Ying"
  },
  {
    id: 14,
    char: "ฎ",
    word: "ชฎา",
    full: "ฎ ชฎา",
    spokenFull: "ดอ ชะดา",
    phonics: "ดอ",
    spokenPhonics: "ออกเสียง ดอ",
    readText: "ฎ ชฎา",
    poem: "ฎอ ชฎา สวมพลัน",
    spokenPoem: "ดอ ชะดา สวมพลัน",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/14.png",
    examples: ["ฎีกา", "กฎหมาย", "มงกุฎ"],
    eng: "Do Cha-da"
  },
  {
    id: 15,
    char: "ฏ",
    word: "ปฏัก",
    full: "ฏ ปฏัก",
    spokenFull: "ตอ ปะตัก",
    phonics: "ตอ",
    spokenPhonics: "ออกเสียง ตอ",
    readText: "ฏ ปฏัก",
    poem: "ฏอ ปฏัก หุนหัน",
    spokenPoem: "ตอ ปะตัก หุนหัน",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/15.png",
    examples: ["ปฏิทิน", "ปฏิบัติ", "ปฏิเสธ"],
    eng: "To Pa-tak"
  },
  {
    id: 16,
    char: "ฐ",
    word: "ฐาน",
    full: "ฐ ฐาน",
    spokenFull: "ถอ ถาน",
    phonics: "ถอ",
    spokenPhonics: "ออกเสียง ถอ",
    readText: "ฐ ฐาน",
    poem: "ฐอ ฐาน เข้ามารอง",
    spokenPoem: "ถอ ถาน เข้ามารอง",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/16.png",
    examples: ["รัฐบาล", "เศรษฐี", "อัฐิ"],
    eng: "Tho Than"
  },
  {
    id: 17,
    char: "ฑ",
    word: "มณโฑ",
    full: "ฑ มณโฑ",
    spokenFull: "ทอ มนโท",
    phonics: "ทอ",
    spokenPhonics: "ออกเสียง ทอ",
    readText: "ฑ มณโฑ",
    poem: "ฑอ มณโฑ หน้าขาว",
    spokenPoem: "ทอ มนโท หน้าขาว",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/17.png",
    examples: ["บัณฑิต", "ครุฑ", "มณฑล"],
    eng: "Tho Montho"
  },
  {
    id: 18,
    char: "ฒ",
    word: "ผู้เฒ่า",
    full: "ฒ ผู้เฒ่า",
    spokenFull: "ทอ ผู้เฒ่า",
    phonics: "ทอ",
    spokenPhonics: "ออกเสียง ทอ",
    readText: "ฒ ผู้เฒ่า",
    poem: "ฒอ ผู้เฒ่า เดินย่อง",
    spokenPoem: "ทอ ผู้เฒ่า เดินย่อง",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/18.png",
    examples: ["พัฒนา", "วัฒนธรรม", "วุฒิ"],
    eng: "Tho Phu-thao"
  },
  {
    id: 19,
    char: "ณ",
    word: "เณร",
    full: "ณ เณร",
    spokenFull: "นอ เณร",
    phonics: "นอ",
    spokenPhonics: "ออกเสียง นอ",
    readText: "ณ เณร",
    poem: "ณอ เณร ไม่มอง",
    spokenPoem: "นอ เณร ไม่มอง",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/19.png",
    examples: ["ณรงค์", "คุณครู", "โบราณ"],
    eng: "No Nen"
  },
  {
    id: 20,
    char: "ด",
    word: "เด็ก",
    full: "ด เด็ก",
    spokenFull: "ดอ เด็ก",
    phonics: "ดอ",
    spokenPhonics: "ออกเสียง ดอ",
    readText: "ด เด็ก",
    poem: "ดอ เด็ก ต้องนิมนต์",
    spokenPoem: "ดอ เด็ก ต้องนิมนต์",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/20.png",
    examples: ["ดาว", "ดอกไม้", "ดินสอ"],
    eng: "Do Dek"
  },
  {
    id: 21,
    char: "ต",
    word: "เต่า",
    full: "ต เต่า",
    spokenFull: "ตอ เต่า",
    phonics: "ตอ",
    spokenPhonics: "ออกเสียง ตอ",
    readText: "ต เต่า",
    poem: "ตอ เต่า หลังตุง",
    spokenPoem: "ตอ เต่า หลังตุง",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/21.png",
    examples: ["ต้นไม้", "โต๊ะ", "แตงโม"],
    eng: "To Tao"
  },
  {
    id: 22,
    char: "ถ",
    word: "ถุง",
    full: "ถ ถุง",
    spokenFull: "ถอ ถุง",
    phonics: "ถอ",
    spokenPhonics: "ออกเสียง ถอ",
    readText: "ถ ถุง",
    poem: "ถอ ถุง แบกขน",
    spokenPoem: "ถอ ถุง แบกขน",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/22.png",
    examples: ["ถ้วย", "ถัง", "ถั่ว"],
    eng: "Tho Thung"
  },

  // แถวที่ 3
  {
    id: 23,
    char: "ท",
    word: "ทหาร",
    full: "ท ทหาร",
    spokenFull: "ทอ ทะหาน",
    phonics: "ทอ",
    spokenPhonics: "ออกเสียง ทอ",
    readText: "ท ทหาร",
    poem: "ทอ ทหาร อดทน",
    spokenPoem: "ทอ ทะหาน อดทน",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/23.png",
    examples: ["ทะเล", "ทอง", "ทุเรียน"],
    eng: "Tho Thahan"
  },
  {
    id: 24,
    char: "ธ",
    word: "ธง",
    full: "ธ ธง",
    spokenFull: "ทอ ทง",
    phonics: "ทอ",
    spokenPhonics: "ออกเสียง ทอ",
    readText: "ธ ธง",
    poem: "ธอ ธง คนนิยม",
    spokenPoem: "ทอ ทง คนนิยม",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/24.png",
    examples: ["เธอ", "ธนู", "ธรรมชาติ"],
    eng: "Tho Thong"
  },
  {
    id: 25,
    char: "น",
    word: "หนู",
    full: "น หนู",
    spokenFull: "นอ หนู",
    phonics: "นอ",
    spokenPhonics: "ออกเสียง นอ",
    readText: "น หนู",
    poem: "นอ หนู ขวักไขว่",
    spokenPoem: "นอ หนู ขวักไขว่",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/25.png",
    examples: ["นก", "น้ำ", "นาฬิกา"],
    eng: "No Nu"
  },
  {
    id: 26,
    char: "บ",
    word: "ใบไม้",
    full: "บ ใบไม้",
    spokenFull: "บอ ใบไม้",
    phonics: "บอ",
    spokenPhonics: "ออกเสียง บอ",
    readText: "บ ใบไม้",
    poem: "บอ ใบไม้ ทับถม",
    spokenPoem: "บอ ใบไม้ ทับถม",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/26.png",
    examples: ["บ้าน", "บอล", "บัว"],
    eng: "Bo Baimai"
  },
  {
    id: 27,
    char: "ป",
    word: "ปลา",
    full: "ป ปลา",
    spokenFull: "ปอ ปลา",
    phonics: "ปอ",
    spokenPhonics: "ออกเสียง ปอ",
    readText: "ป ปลา",
    poem: "ปอ ปลา ตากลม",
    spokenPoem: "ปอ ปลา ตากลม",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/27.png",
    examples: ["เป็ด", "ป่า", "ปากกา"],
    eng: "Po Pla"
  },
  {
    id: 28,
    char: "ผ",
    word: "ผึ้ง",
    full: "ผ ผึ้ง",
    spokenFull: "ผอ ผึ้ง",
    phonics: "ผอ",
    spokenPhonics: "ออกเสียง ผอ",
    readText: "ผ ผึ้ง",
    poem: "ผอ ผึ้ง ทำรัง",
    spokenPoem: "ผอ ผึ้ง ทำรัง",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/28.png",
    examples: ["ผ้า", "ผัก", "ผลไม้"],
    eng: "Pho Phueng"
  },
  {
    id: 29,
    char: "ฝ",
    word: "ฝา",
    full: "ฝ ฝา",
    spokenFull: "ฝอ ฝา",
    phonics: "ฝอ",
    spokenPhonics: "ออกเสียง ฝอ",
    readText: "ฝ ฝา",
    poem: "ฝอ ฝา ทนทาน",
    spokenPoem: "ฝอ ฝา ทนทาน",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/29.png",
    examples: ["ฝน", "ฝรั่ง", "ฝัน"],
    eng: "Fo Fa"
  },
  {
    id: 30,
    char: "พ",
    word: "พาน",
    full: "พ พาน",
    spokenFull: "พอ พาน",
    phonics: "พอ",
    spokenPhonics: "ออกเสียง พอ",
    readText: "พ พาน",
    poem: "พอ พาน วางตั้ง",
    spokenPoem: "พอ พาน วางตั้ง",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/30.png",
    examples: ["พ่อ", "พี่", "พัดลม"],
    eng: "Pho Phan"
  },
  {
    id: 31,
    char: "ฟ",
    word: "ฟัน",
    full: "ฟ ฟัน",
    spokenFull: "ฟอ ฟัน",
    phonics: "ฟอ",
    spokenPhonics: "ออกเสียง ฟอ",
    readText: "ฟ ฟัน",
    poem: "ฟอ ฟัน สะอาดจัง",
    spokenPoem: "ฟอ ฟัน สะอาดจัง",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/31.png",
    examples: ["ฟ้า", "ฟุตบอล", "ฟองน้ำ"],
    eng: "Fo Fan"
  },
  {
    id: 32,
    char: "ภ",
    word: "สำเภา",
    full: "ภ สำเภา",
    spokenFull: "พอ สำเภา",
    phonics: "พอ",
    spokenPhonics: "ออกเสียง พอ",
    readText: "ภ สำเภา",
    poem: "ภอ สำเภา กางใบ",
    spokenPoem: "พอ สำเภา กางใบ",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/32.png",
    examples: ["ภูเขา", "ภาพ", "ภาษา"],
    eng: "Pho Sam-phao"
  },
  {
    id: 33,
    char: "ม",
    word: "ม้า",
    full: "ม ม้า",
    spokenFull: "มอ ม้า",
    phonics: "มอ",
    spokenPhonics: "ออกเสียง มอ",
    readText: "ม ม้า",
    poem: "มอ ม้า คึกคัก",
    spokenPoem: "มอ ม้า คึกคัก",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/33.png",
    examples: ["แม่", "แมว", "มะม่วง"],
    eng: "Mo Ma"
  },

  // แถวที่ 4
  {
    id: 34,
    char: "ย",
    word: "ยักษ์",
    full: "ย ยักษ์",
    spokenFull: "ยอ ยัก",
    phonics: "ยอ",
    spokenPhonics: "ออกเสียง ยอ",
    readText: "ย ยักษ์",
    poem: "ยอ ยักษ์ เขี้ยวใหญ่",
    spokenPoem: "ยอ ยัก เขี้ยวใหญ่",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/34.png",
    examples: ["ยา", "ยิ้ม", "ยางลบ"],
    eng: "Yo Yak"
  },
  {
    id: 35,
    char: "ร",
    word: "เรือ",
    full: "ร เรือ",
    spokenFull: "รอ เรือ",
    phonics: "รอ",
    spokenPhonics: "ออกเสียง รอ",
    readText: "ร เรือ",
    poem: "รอ เรือ พายไป",
    spokenPoem: "รอ เรือ พายไป",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/35.png",
    examples: ["รถ", "ร่ม", "โรงเรียน"],
    eng: "Ro Ruea"
  },
  {
    id: 36,
    char: "ล",
    word: "ลิง",
    full: "ล ลิง",
    spokenFull: "ลอ ลิง",
    phonics: "ลอ",
    spokenPhonics: "ออกเสียง ลอ",
    readText: "ล ลิง",
    poem: "ลอ ลิง ไต่ราว",
    spokenPoem: "ลอ ลิง ไต่ราว",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/36.png",
    examples: ["ลูกบอล", "ลม", "ลำโพง"],
    eng: "Lo Ling"
  },
  {
    id: 37,
    char: "ว",
    word: "แหวน",
    full: "ว แหวน",
    spokenFull: "วอ แหวน",
    phonics: "วอ",
    spokenPhonics: "ออกเสียง วอ",
    readText: "ว แหวน",
    poem: "วอ แหวน ลงยา",
    spokenPoem: "วอ แหวน ลงยา",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/37.png",
    examples: ["วัว", "ว่าว", "แว่นตา"],
    eng: "Wo Waen"
  },
  {
    id: 38,
    char: "ศ",
    word: "ศาลา",
    full: "ศ ศาลา",
    spokenFull: "สอ สาลา",
    phonics: "สอ",
    spokenPhonics: "ออกเสียง สอ",
    readText: "ศ ศาลา",
    poem: "ศอ ศาลา เงียบเหงา",
    spokenPoem: "สอ สาลา เงียบเหงา",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/38.png",
    examples: ["ศิลปะ", "ศุกร์", "ศูนย์"],
    eng: "So Sala"
  },
  {
    id: 39,
    char: "ษ",
    word: "ฤๅษี",
    full: "ษ ฤๅษี",
    spokenFull: "สอ รือสี",
    phonics: "สอ",
    spokenPhonics: "ออกเสียง สอ",
    readText: "ษ ฤๅษี",
    poem: "ษอ ฤๅษี หนวดยาว",
    spokenPoem: "สอ รือสี หนวดยาว",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/39.png",
    examples: ["กระดาษ", "เศษ", "พิษ"],
    eng: "So Ruesi"
  },
  {
    id: 40,
    char: "ส",
    word: "เสือ",
    full: "ส เสือ",
    spokenFull: "สอ เสือ",
    phonics: "สอ",
    spokenPhonics: "ออกเสียง สอ",
    readText: "ส เสือ",
    poem: "สอ เสือ ดาวคะนอง",
    spokenPoem: "สอ เสือ ดาวคะนอง",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/40.png",
    examples: ["สิงโต", "ส้ม", "สมุด"],
    eng: "So Suea"
  },
  {
    id: 41,
    char: "ห",
    word: "หีบ",
    full: "ห หีบ",
    spokenFull: "หอ หีบ",
    phonics: "หอ",
    spokenPhonics: "ออกเสียง หอ",
    readText: "ห หีบ",
    poem: "หอ หีบ ใส่ผ้า",
    spokenPoem: "หอ หีบ ใส่ผ้า",
    group: "อักษรสูง",
    groupColor: "#10b981",
    image: "assets/cards/41.png",
    examples: ["หอย", "ห้อง", "เห็ด"],
    eng: "Ho Hip"
  },
  {
    id: 42,
    char: "ฬ",
    word: "จุฬา",
    full: "ฬ จุฬา",
    spokenFull: "ลอ จุลา",
    phonics: "ลอ",
    spokenPhonics: "ออกเสียง ลอ",
    readText: "ฬ จุฬา",
    poem: "ฬอ จุฬา ท่าผยอง",
    spokenPoem: "ลอ จุลา ท่าผยอง",
    group: "อักษรต่ำเดี่ยว",
    groupColor: "#f59e0b",
    image: "assets/cards/42.png",
    examples: ["กีฬา", "นาฬิกา", "วาฬ"],
    eng: "Lo Chula"
  },
  {
    id: 43,
    char: "อ",
    word: "อ่าง",
    full: "อ อ่าง",
    spokenFull: "ออ อ่าง",
    phonics: "ออ",
    spokenPhonics: "ออกเสียง ออ",
    readText: "อ อ่าง",
    poem: "ออ อ่าง เนืองนอง",
    spokenPoem: "ออ อ่าง เนืองนอง",
    group: "อักษรกลาง",
    groupColor: "#2563eb",
    image: "assets/cards/43.png",
    examples: ["องุ่น", "อาหาร", "โอ่ง"],
    eng: "O Ang"
  },
  {
    id: 44,
    char: "ฮ",
    word: "นกฮูก",
    full: "ฮ นกฮูก",
    spokenFull: "ฮอ นกฮูก",
    phonics: "ฮอ",
    spokenPhonics: "ออกเสียง ฮอ",
    readText: "ฮ นกฮูก",
    poem: "ฮอ นกฮูก ตาโต",
    spokenPoem: "ฮอ นกฮูก ตาโต",
    group: "อักษรต่ำคู่",
    groupColor: "#ea580c",
    image: "assets/cards/44.png",
    examples: ["ฮิปโป", "เฮลิคอปเตอร์", "ฮ่องกง"],
    eng: "Ho Nok-huk"
  }
];

// ข้อมูลหมวดหมู่ไตรยางศ์ (อักษร ๓ หมู่ แบ่งละเอียด: กลาง, สูง, ต่ำเดี่ยว, ต่ำคู่)
const TRIGRAM_DATA = {
  all: {
    title: "พยัญชนะไทยทั้งหมด ๔๔ ตัว",
    spoken: "พยัญชนะไทย ทั้งหมด สี่สิบสี่ ตัว",
    count: 44,
    color: "#ffffff"
  },
  mid: {
    title: "อักษรกลาง (๙ ตัว)",
    letters: ["ก", "จ", "ฎ", "ฏ", "ด", "ต", "บ", "ป", "อ"],
    rule: "ไก่ จิก เด็ก ตาย บน ปาก โอ่ง",
    spoken: "อักษรกลาง มีทั้งหมด เก้า ตัว ได้แก่ กอ, จอ, ดอ ชะดา, ตอ ปะตัก, ดอ เด็ก, ตอ เต่า, บอ ใบไม้, ปอ ปลา, ออ อ่าง. ท่องจำว่า ไก่ จิก เด็ก ตาย บน ปาก โอ่ง",
    count: 9,
    color: "#2563eb"
  },
  high: {
    title: "อักษรสูง (๑๑ ตัว)",
    letters: ["ข", "ฃ", "ฉ", "ฐ", "ถ", "ผ", "ฝ", "ศ", "ษ", "ส", "ห"],
    rule: "ผี ฝาก ถุง ข้าว สาร ให้ ฉัน",
    spoken: "อักษรสูง มีทั้งหมด สิบเอ็ด ตัว ได้แก่ ขอ ไข่, ขอ ขวด, ฉอ ฉิ่ง, ฐอ ถาน, ถอ ถุง, ผอ ผึ้ง, ฝอ ฝา, ศอ สาลา, ษอ รือสี, สอ เสือ, หอ หีบ. ท่องจำว่า ผี ฝาก ถุง ข้าว สาร ให้ ฉัน",
    count: 11,
    color: "#10b981"
  },
  'low-single': {
    title: "อักษรต่ำเดี่ยว (๑๐ ตัว)",
    letters: ["ง", "ญ", "ณ", "น", "ม", "ย", "ร", "ล", "ว", "ฬ"],
    rule: "งู ใหญ่ นอน อยู่ ณ ริม วัด โม ฬี โลก",
    spoken: "อักษรต่ำเดี่ยว มีทั้งหมด สิบ ตัว ได้แก่ งอ งู, ยอ หญิง, นอ เณร, นอ หนู, มอ ม้า, ยอ ยักษ์, รอ เรือ, ลอ ลิง, วอ แหวน, ลอ จุฬา. ท่องจำว่า งู ใหญ่ นอน อยู่ ณ ริม วัด โม ฬี โลก",
    count: 10,
    color: "#f59e0b"
  },
  'low-pair': {
    title: "อักษรต่ำคู่ (๑๔ ตัว)",
    letters: ["ค", "ฅ", "ฆ", "ช", "ซ", "ฌ", "ฑ", "ฒ", "ท", "ธ", "พ", "ฟ", "ภ", "ฮ"],
    rule: "พ่อ ค้า ฟัน ทอง ซื้อ ช้าง ฮ่อ",
    spoken: "อักษรต่ำคู่ มีทั้งหมด สิบสี่ ตัว ได้แก่ คอ ควาย, คอ คน, คอ ระฆัง, ชอ ช้าง, ซอ โซ่, ชอ เฌอ, ทอ มณโฑ, ทอ ผู้เฒ่า, ทอ ทหาร, ทอ ธง, พอ พาน, ฟอ ฟัน, พอ สำเภา, ฮอ นกฮูก. ท่องจำว่า พ่อ ค้า ฟัน ทอง ซื้อ ช้าง ฮ่อ",
    count: 14,
    color: "#ea580c"
  },
  low: {
    title: "อักษรต่ำ (๒๔ ตัว)",
    letters: [
      "ค", "ฅ", "ฆ", "ง", "ช", "ซ", "ฌ", "ญ", "ฑ", "ฒ", "ณ",
      "ท", "ธ", "น", "พ", "ฟ", "ภ", "ม", "ย", "ร", "ล", "ว", "ฬ", "ฮ"
    ],
    rule: "ต่ำเดี่ยว ๑๐ ตัว, ต่ำคู่ ๑๔ ตัว",
    spoken: "อักษรต่ำ มีทั้งหมด ยี่สิบสี่ ตัว แบ่งเป็น อักษรต่ำเดี่ยว สิบ ตัว และ อักษรต่ำคู่ สิบสี่ ตัว",
    count: 24,
    color: "#f59e0b"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { THAI_ALPHABET_DATA, TRIGRAM_DATA };
}
